//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVehicular.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARS_ReportsCar
    {
        public int Id { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> ReportTypeId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Lights { get; set; }
        public Nullable<bool> QuarterLights { get; set; }
        public Nullable<bool> Antenna { get; set; }
        public Nullable<bool> RightMirror { get; set; }
        public Nullable<bool> LeftMirror { get; set; }
        public Nullable<bool> Crystals { get; set; }
        public Nullable<bool> Emblem { get; set; }
        public Nullable<bool> Tires { get; set; }
        public Nullable<bool> Caps { get; set; }
        public Nullable<bool> Views { get; set; }
        public Nullable<bool> GasolineStopper { get; set; }
        public Nullable<bool> Dents { get; set; }
        public Nullable<bool> Horn { get; set; }
        public Nullable<bool> DashboardInstruments { get; set; }
        public Nullable<bool> Ac { get; set; }
        public Nullable<bool> Windshield { get; set; }
        public Nullable<bool> Radio { get; set; }
        public Nullable<bool> Speakers { get; set; }
        public Nullable<bool> Lighter { get; set; }
        public Nullable<bool> RearviewMirror { get; set; }
        public Nullable<bool> Ashtray { get; set; }
        public Nullable<bool> SeatBelts { get; set; }
        public Nullable<bool> InteriorButtons { get; set; }
        public Nullable<bool> InteriorHandles { get; set; }
        public Nullable<bool> Mats { get; set; }
        public Nullable<bool> CarTrim { get; set; }
        public Nullable<bool> Jack { get; set; }
        public Nullable<bool> JackHandle { get; set; }
        public Nullable<bool> WheelWrench { get; set; }
        public Nullable<bool> ToolKit { get; set; }
        public Nullable<bool> ReflectingTriangle { get; set; }
        public Nullable<bool> SpareTire { get; set; }
        public Nullable<bool> FireExtinguisher { get; set; }
        public string GasTank { get; set; }
        public string Observations { get; set; }
        public string Mileage { get; set; }
        public Nullable<System.DateTime> NextService { get; set; }
        public string LifePilotFrontTire { get; set; }
        public string ObservPilotFrontTire { get; set; }
        public string LifePassengerFrontTire { get; set; }
        public string ObservPassengerFrontTire { get; set; }
        public string LifePilotRearTire { get; set; }
        public string ObservPilotRearTire { get; set; }
        public string LifePassengerRearTire { get; set; }
        public string ObservnPassengerRearTire { get; set; }
        public string LifeExtraTire { get; set; }
        public string ObservExtraTire { get; set; }
        public string GeneralCondition { get; set; }
        public string ConditionsTravel { get; set; }
        public string PhotoEvidence { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
