//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVehicular.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARS_Cars
    {
        public int Id { get; set; }
        public string ItemCode { get; set; }
        public string Model { get; set; }
        public string Department { get; set; }
        public string Assigned { get; set; }
        public string LicencePlate { get; set; }
        public string Mark { get; set; }
        public string Year { get; set; }
        public string CirculationCard { get; set; }
        public string InsuranceCompany { get; set; }
        public string SecurityNumber { get; set; }
        public string RegisteredIn { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
