//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVehicular.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CONTROL_VEHICULAR_Entities : DbContext
    {
        public CONTROL_VEHICULAR_Entities()
            : base("name=CONTROL_VEHICULAR_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARS_Cars> CARS_Cars { get; set; }
        public virtual DbSet<CARS_ReportsCar> CARS_ReportsCar { get; set; }
        public virtual DbSet<CARS_ReportTypes> CARS_ReportTypes { get; set; }
        public virtual DbSet<USERS_Users> USERS_Users { get; set; }
        public virtual DbSet<USERS_UserTypes> USERS_UserTypes { get; set; }
        public virtual DbSet<View_CarLoans> View_CarLoans { get; set; }
        public virtual DbSet<View_LastsLoans> View_LastsLoans { get; set; }
        public virtual DbSet<View_ServicesMoreSixMonths> View_ServicesMoreSixMonths { get; set; }
    }
}
