//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlVehicular.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_CarLoans
    {
        public int Id { get; set; }
        public string Assigned { get; set; }
        public string Model { get; set; }
        public string LicencePlate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ReportId { get; set; }
    }
}
